controllers/AdminController.php
<?php

namespace app\controllers;

use Yii;
use yii\web\Controller;
use yii\web\UploadedFile;

use app\models\Order;
use app\models\Category;
use app\models\Event;
use app\models\User;
use app\models\ImageUpload;


class AdminController extends Controller {

	public $layout = 'admin';

	public function behaviors() {
		return [
		];
	}

	public function actions() {
		return [
			'error' => [
				'class' => 'yii\web\ErrorAction',
			],
			'captcha' => [
				'class' => 'yii\captcha\CaptchaAction',
				'fixedVerifyCode' => YII_ENV_TEST ? 'testme' : null,
			],
		];
	}

	public function beforeAction($action) {

		if (Yii::$app->user->isGuest) {
			return $this->redirect('/auth/login');
		}

		return parent::beforeAction($action);
	}

	public function actionIndex() {
		$orders = Order::find()->orderBy(['id' => SORT_DESC])->limit(10)->all();

		return $this->render('index',[
			'orders'=>$orders,
		]);
	}

	public function actionOrders() {
		$orders = Order::find()->orderBy(['id' => SORT_DESC])->all();

		return $this->render('orders',[
			'orders'=>$orders,
		]);
	}

	public function actionUsers() {

		$this->check_admin();

		$users = User::find()->all();

		return $this->render('user-list',[
			'users'=>$users,
		]);
	}


	public function actionCats() {

		$this->check_admin();

		$categories = Category::find()->orderBy(['id' => SORT_DESC])->all();

		return $this->render('cats',[
			'categories'=>$categories,
		]);
	}

	public function actionCatAdd() {

		$this->check_admin();

		$model = new Category();

		if($model->load(Yii::$app->request->post()) and $model->save()){
			return $this->redirect('/admin/cats');
		}

		return $this->render('cat-add',[
			'model'=>$model,
		]);
	}

	public function actionCatEdit($id) {

		$this->check_admin();

		$model = Category::findOne($id);

		if($model->load(Yii::$app->request->post()) and $model->save()){
			return $this->redirect('/admin/cats');
		}

		return $this->render('cat-edit',[
			'model'=>$model,
		]);
	}

	public function actionCatDelete($id) {

		$this->check_admin();

		$model = Category::findOne($id);
		$model->delete();

		return $this->redirect(['/admin/cats']);
	}


	public function actionEvent() {
		$this->check_admin();

		$events = Event::find()->orderBy(['id' => SORT_DESC])->all();

		return $this->render('events',[
			'events'=>$events,
		]);
	}

	public function actionEventAdd() {

		$this->check_admin();

		$model = new Event();
		$model_iu = new ImageUpload;

		if($model->load(Yii::$app->request->post())){

			$file = UploadedFile::getInstance($model,'image');
			if($file != null)
				$model->image = $model_iu->uploadFile($file, $model->image);

			if($model->save()){
				return $this->redirect('/admin/event');
			}

		}

		return $this->render('event-add',[
			'model_iu'=>$model_iu,
			'model'=>$model,
		]);
	}

	public function actionEventEdit($id) {

		$this->check_admin();

		$model = Event::findOne($id);
		$model_iu = new ImageUpload;

		if($model->load(Yii::$app->request->post())){

			$file = UploadedFile::getInstance($model,'image');
			if($file != null)
				$model->image = $model_iu->uploadFile($file, $model->image);

			if($model->save()){
				return $this->redirect('/admin/event');
			}

		}

		return $this->render('event-edit',[
			'model'=>$model,
		]);
	}

	public function actionEventDelete($id) {

		$this->check_admin();

		$model = Event::findOne($id);
		$model->delete();

		return $this->redirect(['/admin/event']);
	}


	public function check_admin(){
		if(!User::is_admin())
			return $this->redirect('/admin/index');
	}

}

controllers/AuthController.php
<?php

namespace app\controllers;

use Yii;
use yii\web\Controller;

use app\models\LoginForm;
use app\models\SignupForm;
use app\models\User;

class AuthController extends Controller
{

	public function actionLogin()
	{
		if (!Yii::$app->user->isGuest) {
			return $this->goHome();
		}
		$model = new LoginForm();
		if ($model->load(Yii::$app->request->post()) && $model->login()) {
			return $this->goBack();
		}
		return $this->render('login', [
			'model' => $model,
		]);
	}

	public function actionLogout()
	{
		Yii::$app->user->logout();
		return $this->goHome();
	}

	public function actionSignup()
	{
		$model = new SignupForm();

		if(Yii::$app->request->isPost)
		{
			$model->load(Yii::$app->request->post());
			if($model->signup())
			{
				return $this->redirect(['auth/login']);
			}
		}

		return $this->render('signup', ['model'=>$model]);
	}
}

views/layouts/account.php
<?php

/* @var $this \yii\web\View */
/* @var $content string */

use yii\helpers\Html;
use app\models\User;
use app\assets\UserAsset;

UserAsset::register($this);
$user = User::findOne(Yii::$app->user->id);
$admin = $user->is_admin == 1;
?>
<?php $this->beginPage() ?>
<!DOCTYPE html>
<html lang="<?= Yii::$app->language ?>">
<head>
	<meta charset="<?= Yii::$app->charset ?>">
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<?= Html::csrfMetaTags() ?>
	<title><?= Html::encode($this->title) ?></title>
	<?php $this->head() ?>
	<!--[if lt IE 9]>
		<script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
	<![endif]-->
</head>
<body class=" theme-blue">

	<?php $this->beginBody() ?>
	<?= $this->render('/partials/navbar-ac', ['user' => $user]);?>

	<?php if ($admin): ?>
		<?= $this->render('/partials/sidebar-ac');?>
	<?php endif ?>

	<div class="content" <?= !$admin ? 'style="margin-left:0"': '' ?>>
		<?= $content ?>
	</div>

	<?php $this->endBody() ?>
<?php $this->registerJsFile('/ckeditor/ckeditor.js');?>
<?php $this->registerJsFile('/ckfinder/ckfinder.js');?>
<script>
	$(document).ready(function(){
		var editor = CKEDITOR.replaceAll();
		CKFinder.setupCKEditor( editor );
	})
</script>
</body>
</html>
<?php $this->endPage() ?>

views/layouts/admin.php
<?php

/* @var $this \yii\web\View */
/* @var $content string */

use yii\helpers\Html;
use yii\bootstrap\Nav;
use yii\bootstrap\NavBar;
use yii\widgets\Breadcrumbs;
use app\assets\AppAsset;

AppAsset::register($this);
?>
<?php $this->beginPage() ?>
<!DOCTYPE html>
<html lang="<?= Yii::$app->language ?>">
<head>
    <meta charset="<?= Yii::$app->charset ?>">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <?= Html::csrfMetaTags() ?>
    <title><?= Html::encode($this->title) ?></title>
    <?php $this->head() ?>
</head>
<body>
<?php $this->beginBody() ?>

<div class="wrap">
    <?php
    NavBar::begin([
        'brandLabel' => 'Админка билетной кассы',
        'brandUrl' => ['/admin/index'],
        'options' => [
            'class' => 'navbar-inverse',
        ],
    ]);
    echo Nav::widget([
        'options' => ['class' => 'navbar-nav navbar-right'],
        'items' => [
            ['label' => 'Пользователи', 'url' => ['/admin/users']],
            ['label' => 'Билеты', 'url' => ['/admin/event']],
            ['label' => 'Афиша', 'url' => ['/admin/cats']],
            ['label' => 'Заказы', 'url' => ['/admin/orders']],
            ['label' => 'Выход', 'url' => ['/auth/logout']],
        ],
    ]);
    NavBar::end();
    ?>

    <div class="container">
        <?= Breadcrumbs::widget([
            'links' => isset($this->params['breadcrumbs']) ? $this->params['breadcrumbs'] : [],
        ]) ?>
        <?= $content ?>
    </div>
</div>

<?php $this->endBody() ?>
<?php $this->registerJsFile('/ckeditor/ckeditor.js');?>
<?php $this->registerJsFile('/ckfinder/ckfinder.js');?>
<script>
    $(document).ready(function(){
        var editor = CKEDITOR.replaceAll();
        CKFinder.setupCKEditor( editor );
    })

</script>
</body>
</html>
<?php $this->endPage() ?>

views/layouts/main.php
<?php

/* @var $this \yii\web\View */
/* @var $content string */

use yii\helpers\Html;
use yii\bootstrap\Nav;
use yii\bootstrap\NavBar;
use yii\helpers\Url;
use yii\widgets\Breadcrumbs;

use app\assets\PublicAsset;

PublicAsset::register($this);
?>
<?php $this->beginPage() ?>
<!DOCTYPE html>
<html lang="<?= Yii::$app->language ?>">
<head>
	<meta charset="<?= Yii::$app->charset ?>">
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<?= Html::csrfMetaTags() ?>
	<title><?= Html::encode($this->title) ?></title>
	<?php $this->head() ?>

	<!-- Behavioral Meta Data -->
	<meta name="apple-mobile-web-app-capable" content="yes">
	<meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no">
</head>
<body class="sticky_footer">
	<?php $this->beginBody() ?>

	<div id="fh5co-wrapper">
		<div id="fh5co-page">
			<?= $this->render('/partials/header');?>
			<?= $content ?>
			<?= $this->render('/partials/footer');?>
		</div>
	</div>
	<?php $this->endBody() ?>
</body>
</html>
<?php $this->endPage() ?>